version: '3.9'

services:
  app:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" #Ставим порт 8080
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    container_name: db
    build: 
      context: .
      dockerfile: DockerfileP
    environment:
      POSTGRES_USER: max
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: bus
    ports:
      - "5500:5500" # Ставим порт 5500
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
